quick test

diff --git a/.github/workflows/pull_request_push_test.yml b/.github/workflows/pull_request_push_test.yml
--- a/.github/workflows/pull_request_push_test.yml
+++ b/.github/workflows/pull_request_push_test.yml
@@ -304,7 +304,8 @@ jobs:
     steps:
       - name: Check gradle test status
         run: |
-          echo "test"
+          echo "test status failed"
+          exit 1
        
   failure_notification:
     # If any failure, warning message will be sent
