test

diff --git a/.github/workflows/pull_request_push_test.yml b/.github/workflows/pull_request_push_test.yml
--- a/.github/workflows/pull_request_push_test.yml
+++ b/.github/workflows/pull_request_push_test.yml
@@ -302,7 +302,7 @@ jobs:
 
   registry_test:
     runs-on: ubuntu-latest
-    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && (contains(github.event.pull_request.labels.*.name, 'registry test') || contains(github.event.pull_request.labels.*.name, 'safe to test')))
+    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'registry test'))
     steps:
       - uses: actions/checkout@v2
         with:
@@ -337,8 +337,8 @@ jobs:
     # The status used to mark if any required test jobs failed for a PR
     # If it's failure, PR will be blocked
     runs-on: ubuntu-latest
-    if: always() && github.event_name == 'pull_request_target'
-    needs: [gradle_test, python_lint, databricks_test, azure_synapse_test, local_spark_test, registry_test, paths_filter]
+    if: always() && github.event_name == 'pull_request'
+    needs: [gradle_test, python_lint, databricks_test, azure_synapse_test, local_spark_test, paths_filter]
     steps:
       - name: Test status failure
         if: contains(needs.*.result, 'failure')
@@ -346,20 +346,20 @@ jobs:
           echo "Merging is blocked because one or more test jobs failed."
           exit 1
       - name: Required test cases skipped
-        if: contains(needs.*.result, 'skipped') && needs.paths_filter.outputs.output1 != 'true' && needs.paths_filter.outputs.output2 != 'true'
+        if: contains(needs.*.result, 'skipped') && needs.paths_filter.outputs.output1 == 'true'
         run: |
           echo "Merging is blocked because some required test jobs didn't run. Please set the label 'safe to test'"
           exit 1
       - name: Test status success
-        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'skipped') || (contains(needs.*.result, 'skipped') && (needs.paths_filter.outputs.output1 == 'true' || needs.paths_filter.outputs.output2 == 'true'))}}
+        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'skipped') || ( contains(needs.*.result, 'skipped') && needs.paths_filter.outputs.output1 != 'true' )}}
         run: |
-          echo "All required CI test jobs for python client passed."
+          echo "All required CI test jobs for client source passed."
 
   registry_test_status:
     # The status used to mark if any required registry test cases failed for a PR
     # If it's failure, PR will be blocked
     runs-on: ubuntu-latest
-    if: always() && github.event_name == 'pull_request_target'
+    if: always() && github.event_name == 'pull_request'
     needs: [registry_test, paths_filter]
     steps:
       - name: Test status failure
@@ -370,7 +370,7 @@ jobs:
       - name: Required test cases skipped
         if: needs.registry_test.result == 'skipped' && needs.paths-filter.outputs.output2 == 'true'
         run: |
-          echo "Merging is blocked because the required 'registry_test' jobs didn't run. Please set the label 'safe to test'"
+          echo "Merging is blocked because the required 'registry_test' jobs didn't run. Please set the label 'registry test'"
           exit 1
       - name: Test status success
         if: needs.registry_test.result == 'success' || needs.registry_test.result == 'skipped' && needs.paths-filter.outputs.output2 != 'true'
