quick test

diff --git a/.github/workflows/pull_request_push_test.yml b/.github/workflows/pull_request_push_test.yml
--- a/.github/workflows/pull_request_push_test.yml
+++ b/.github/workflows/pull_request_push_test.yml
@@ -86,7 +86,7 @@ jobs:
 
   python_lint:
     runs-on: ubuntu-latest
-    if: github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'pull_request' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test'))
+    if: github.event_name == 'schedule' || github.event_name == 'push' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'safe to test'))
     steps:
       - name: Set up Python 3.8
         uses: actions/setup-python@v2
@@ -346,15 +346,15 @@ jobs:
         run: |
           echo "Merging is blocked because one or more test jobs failed."
           exit 1
-      #- name: Required test cases skipped
-      #  if: contains(needs.*.result, 'skipped') && needs.paths-filter.outputs.output1 != 'true' && needs.paths-filter.outputs.output2 != 'true'
-      #  run: |
-      #    echo "Merging is blocked because some required test jobs didn't run. Please set the label 'safe to test'"
-      #    exit 1
-      #- name: Test status success
-      #  if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'skipped') || (contains(needs.*.result, 'skipped') && (needs.paths-filter.outputs.output1 == 'true' || needs.paths-filter.outputs.output2 == 'true'))}}
-      #  run: |
-      #    echo "All required CI test cases for python client passed."
+      - name: Required test cases skipped
+        if: contains(needs.*.result, 'skipped') && needs.paths-filter.outputs.output1 != 'true' && needs.paths-filter.outputs.output2 != 'true'
+        run: |
+          echo "Merging is blocked because some required test jobs didn't run. Please set the label 'safe to test'"
+          exit 1
+      - name: Test status success
+        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'skipped') || (contains(needs.*.result, 'skipped') && (needs.paths-filter.outputs.output1 == 'true' || needs.paths-filter.outputs.output2 == 'true'))}}
+        run: |
+          echo "All required CI test cases for python client passed."
        
   failure_notification:
     # If any failure, warning message will be sent
